### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zunichky/railsFirstProject#1]
Looking very nice. Just one nitpicky thing I'd like you to update: [these two inconsistently indented lines](https://github.com/zunichky/railsFirstProject/blob/master/app/assets/stylesheets/static.scss#L14-L15). Then another tip (though this one is *not* something you have to fix and you are not expected to have known this) is that since we can use SCSS in Rails, the following could be rewritten:

``` css
.header ul {
  margin: 0;
  padding-top: 20px;
}

.header li {
  display: inline;
  padding-right: 40px
}

.header a:hover {
  color: yellow;
}

.header {
  height: 60px;
  background-color: black;
  margin-left: -50px;
}
```

as:

``` scss
.header {
  height: 60px;
  background-color: black;
  margin-left: -50px;
  
  ul {
    margin: 0;
    padding-top: 20px;
  }

  li {
    display: inline;
    padding-right: 40px
  }

  a:hover {
    color: yellow;
  }
}
```

We can nest rules, to give our CSS a little more visual structure! :smiley:
